DELETE http://localhost:3001/api/auth
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImEud2hpdGUiLCJpZCI6IjY1OWQ4NjIyZThkZTNlY2RhOTU3ZGVlYyIsImlhdCI6MTcwNDgyMjg1MiwiZXhwIjoxNzA0ODI2NDUyfQ.LoWPEWq3rlPIc3c_ZReNJkE5sjjvcdY1S3Vrzmu-9mI